### ISSUE TITLE
Add generic lens constructor for spherical singlets

### ISSUE THREAD

**Issue by mattngc** [raysect/source#1]
Currently we have some smart lens builders with validators for the "planar" and "bi" lenses, four of the six fundamental spherical lenses. The meniscus lens are more dificult to validate because to degeneracy issues. Instead it would be better to have a general purpose lens constructor that can work for any spherical lens and performs simpler validation.

**Comment by mattngc** [comment]
The generic lens factory functions for the generic lens geometry should live inside raysect primitives. They could be inherited from Intersection or some other CSG geometry primitive.

**Comment by mattngc** [comment]
Agreed the Alex will do a prototype of the interface he wants. This could be pseudocode. Either of us can then finish the code based on the specified interface. Needs to support both types of initialisation, through base properties (i.e. width, height, radius) and optical properties (i.e. focal length, aperture stop).

**Comment by CnlPepper** [comment]
I've build a Biconvex lens primitive to act as a template for lens/optical primitives that are constructed using CSG primitives. This uses a new EncapsulatedPrimitive class to hide the CSG primitives "inside" the lens primitive (it holds it's own scene-graph internally - note: this scene-graph can only have a single primitive directly attached to the root node). The lens code is now relatively simple to build, just set up the CSG hierarchy and attach.

Alternative initialisations can be added as class methods, these will be custom for each lens type. The class methods should just calculate the appropriate lens dimensions and build the lens by instancing the class.

See commit 63e292bada8b4f2f3cb8ad299205850169267228

**Comment by mattngc** [comment]
premature closure

**Comment by CnlPepper** [comment]
Closed by 8640d0cccc14a0fe6bd236cc62870ac00e395a65.
