### ISSUE TITLE
Orthogonal projection camera

### ISSUE THREAD

**Issue by CocoBis** [raysect/source#10]
A useful feature would be a built in orthogonal projection camera, which fires parallel rays from a regular grid of sources and return a grid of pixels. This would allow to have a schematic view of the world and to avoid perspective effects unlike the pinhole camera. Moreover there is almost nothing to change from the pinhole camera to get it.

**Comment by mattngc** [comment]
Added in commit 1186d551a621a7cefb41fc6e047cad115a0a05f8.
