### ISSUE TITLE
Add an analytic camera as an alternative to the vector camera

### ISSUE THREAD

**Issue by CnlPepper** [raysect/source#109]
Need vector interpolation (using quaternions?) to implement a basic level of anti-aliasing. For non-rectilinear arrays the interpolation domain will be a linear approximation.

**Comment by mattngc** [comment]
We'd prefer to move to an analytic alternative to vector camera. For example we might use an analytic camera model from OpenCV, users would supply the coefficients for their camera calibration.

**Comment by mattngc** [comment]
Looks like the best available analytic camera model is the opencv model. The various parameters and coefficients are explained here.

https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html
https://docs.opencv.org/3.1.0/dc/dbb/tutorial_py_calibration.html

**Comment by mattngc** [comment]
Even better reference.
https://docs.opencv.org/3.4.0/d9/d0c/group__calib3d.html

**Comment by mattngc** [comment]
Work on this in 2898295acd03560067dac23094c5c3a90d09832f and 4063de5a2b48ef1ccc92704a3259de3e8038a767

**Comment by mattngc** [comment]
The OpenCV camera provides an analytic camera alternative and has now been merged into the development branch for Release v0.5.
