### ISSUE TITLE
Scientific accuracy tests

### ISSUE THREAD

**Issue by mattngc** [raysect/source#118]
We need some standard test cases to prove Raysect is scientifically accurate. Examples could include:
- geometric optics
- inverse square fall off
- integrating sphere

**Comment by mattngc** [comment]
This should include both demo .py files and dedicated unit tests for some of the most important energy conservation cases.

**Comment by CnlPepper** [comment]
Basic accuracy tests completed and tested. See commit 1ec9d8578c2b759b7cc95c849dac53645ad61a2c.
