### ISSUE TITLE
Rename spectral attributes

### ISSUE THREAD

**Issue by CnlPepper** [raysect/source#122]
With the development of the observer classes it has become apparent there are a number of attribute names that are beginning to clash or are less descriptive than they could be. The following items could be renamed:

* min_wavelength/max_wavelength --> lower, upper with _wavelength appended when outside a specifically spectral class
* a spectral_range tuple should be used in place of lower/upper wavelength where appropriate, the lower/upper attributes should remain present on the classes for fast C access
* num_samples and spectral_sample should be renamed bins/spectral_bins
* pixel_samples should be simply renamed samples to be consistent with pixels

**Comment by mattngc** [comment]
Partially addressed as part of the observer refactoring. spectral_samples has now become spectral_bins.

**Comment by mattngc** [comment]
We've decided that extra changes will cause more trouble than they are worth. Probably not worth the effort at the moment.
