### ISSUE TITLE
Rebuild kdTree for meshes

### ISSUE THREAD

**Issue by mattngc** [raysect/source#13]
The kdTree needs to be rebuilt and optimised for meshes. Should be rebuilt such that it can support both meshes and other primitives. Optimised for speed, etc.

**Comment by mattngc** [comment]
From what I understand this is mostly finished. Can you just tidy up and merge to master?

**Comment by CnlPepper** [comment]
As it happens I was working on it this evening :) See: da4efe24fe408841517ecbf2192cf3878344a7ba
