### ISSUE TITLE
Documentation build broken

### ISSUE THREAD

**Issue by mattngc** [raysect/source#134]
* There are some problems with the docs building on readthedocs.
* Might be related to CSS overrides in the sphinx theme.

**Comment by CnlPepper** [comment]
Readthedoc builds are timing out due to the length of the cython build. We will move to github pages for now as it is currently impossible to reliably compile the documentation.

**Comment by mattngc** [comment]
Documentation has moved to the github hosting. CSS issues resolved in d03b1d8.
