### ISSUE TITLE
Allow volume materials to have pluggable integrators

### ISSUE THREAD

**Issue by mattngc** [raysect/source#142]
* Currently materials that are volume emitters have a hard coded Simpson's rule integration routine. This is not always optimal, especially when the material has steep gradients in emissivity, or when we have advance knowledge of the structure of the emission (i.e. mesh based emitters).
* Ideally, volume emitting materials would accept a pluggable integrator that defaults to the simple Simpson's rule routine, but can be replaced with more advanced integrators when required.
* Examples of available integrators could include Simpson's rule, dynamic step integrators, mesh traversal integrators.

**Comment by CnlPepper** [comment]
Functionality added in commit a9d460400a71c4a5b6891f5869d55bad1a94a54b.
