### ISSUE TITLE
kdTree2d nesting limit

### ISSUE THREAD

**Issue by mattngc** [raysect/source#144]
* Testing of the kdTree2D with 2D triangular meshes has revealed some suspicious behavior. BoundingBox2Ds at the lowest levels of the tree appear smaller than the triangles they enclose. Cost function in kd-Tree initialisation should not allow this kind of behavior.

**Comment by CnlPepper** [comment]
After experimentation, it was determined that this was not a bug. It is an artefact of the test mesh being poorly conditioned, as well as the kd tree currently not supporting item refinement (e.g. triangle splitting). A new issue will be opened for this enhancement.
