### ISSUE TITLE
Partial Observations?

### ISSUE THREAD

**Issue by jjjar** [raysect/source#146]
Are there any plans to allow for partial (controlled) observations of a scene? Something like observe(bottom_pixel, top_pixel, pixel_samples)? So an observer initialized with pixels (512,512) could call observe((64,64),(128,128),10) to perform 10 pixel samples within that subregion.

**Comment by CnlPepper** [comment]
Hello jjjar,

it is possible to achieve this using a custom frame sampler. At the start of the observer process (for the 1D and 2D observers) the pixels to render are requested from the observer's frame sampler. This could be all the pixels or a subset. In the raysect/optical/observer/sampler2d.py you'll find the code for the default FullFrameSampler2D to use as a reference. The pixel samples is a property of the observer and is not configurable per pixel at present.

I apologise for the lack of documentation covering the observers, we only recently finished the code and will be going back to address it shortly.

Just a small note on the pixel samples setting: it is best to keep this set to at least 100-200 as there is a non-negligible IPC overhead passing data to and from the render processes. A single task passed to the worker processes should contain enough "work" to mitigate the cost of communicating the task/results. For example, performing 10 passes of 10 samples is much slower than performing 1 pass of 100 samples.

**Comment by mattngc** [comment]
Hi jjjar,

Could you describe a little more about your use case for this? Maybe there are a few pixels in your image that require extra sampling due to high noise in these pixels? If this is the case, then we have recently implemented adaptive sampling for the RGB camera which should automatically assign extra samples to noisy pixels. Are you using the latest release?

**Comment by mattngc** [comment]
Assumed fixed.
