### ISSUE TITLE
Vectored Camera

### ISSUE THREAD

**Issue by mattngc** [raysect/source#15]
Some applications will require raysect to use a camera defined by an external party. For example, the camera may have already been calibrated in terms of its distortion and spatial properties. One option is to make a Camera class where every pixel maps to a sight line vector. The array of vectors can be supplied by the user. Another option is to specify a camera in terms of its optics, i.e. lens types, focal length, etc. But this will be left to a later date.

**Comment by CnlPepper** [comment]
Vector camera add and code restructured to simplify camera code.
Completed in commit 7e19019bf5bc95ac984e246e7375b36f08eb2073
