### ISSUE TITLE
Obeserver output and number of rays

### ISSUE THREAD

**Issue by Eclipse17** [raysect/source#172]
Is it possible to create an observer that outputs a total power received or total number of photons received (somewhat akin to a photomultiplier tube)? Additionally, is there a way to control how many rays are used in  a given simulation (in order to compare various geometric setups by how much light reaches certain points)? Thanks!

**Comment by mattngc** [comment]
Hi Eclipse17,

Most of our observers accept a "pipelines" argument, which is a list of post-processing objects. For example, in the latest version of the cornell box:

```python
from raysect.optical.observer import RGBPipeline2D, BayerPipeline2D, SpectralPipeline2D, PowerPipeline2D

power_unfiltered = PowerPipeline2D(display_unsaturated_fraction=0.96, name="Unfiltered")
rgb = RGBPipeline2D(display_unsaturated_fraction=0.96, name="sRGB")
spectral = SpectralPipeline2D()
pipelines = [rgb, power_unfiltered, spectral]

camera = PinholeCamera((512, 512), parent=world, pipelines=pipelines)
```

So in this case, the power pipeline would return the actual power in W collected by the observer. In the case of the optical fibre the pipeline list is the first argument and would be:

```python
spectra = SpectralPipeline0D()
power = PowerPipeline0D()
fibre = FibreOptic([spectra, power], acceptance_angle=45, radius=0.0005, spectral_bins=500, spectral_rays=1, pixel_samples=1000, transform=translate(0, 0, -5), parent=world)
```

You can read about them more here:
https://raysect.github.io/documentation/api_reference/optical/pipelines.html#power

Notice above the "pixel_samples=1000" argument. This parameter controls the number of rays fired per pixel. So in a 2D camera this would be 1000x512x512 rays. In a 0D optical fibre this would be 1000x1 rays. Here, 0D in our observers means an observer with a single pixel, 1D would mean a 1D array of pixels, etc.

Does this help? I will try to post an example of how to calculate etendue over the weekend.

Regards,
Matt

**Comment by Eclipse17** [comment]
Hi Matt,

This helps - thanks so much for your assistance!
