### ISSUE TITLE
Physical pinhole camera

### ISSUE THREAD

**Issue by mattngc** [raysect/source#194]
* The current pinhole camera isn't physical, it uses a very constrained ray geometry with zero etendue. Although the mean Radiance is usable, power makes no sense with this camera.
* As an alternative, we could offer a physical pinhole camera. Arguments could include pinhole radius, distance to CCD and CCD dimensions.
* CCD would use the new targeted pixel functionality for speed.

**Comment by CnlPepper** [comment]
Added a demo with a pinhole camera using a TargettedCCDArray.
