### ISSUE TITLE
Raysect only works for python 3.5 or higher

### ISSUE THREAD

**Issue by mattngc** [raysect/source#197]
Documentation incorrectly states that raysect works for python >= 3.3. In actual fact it should be python >= 3.5. This is due to some of the latest cython features we are using.

**Comment by mattngc** [comment]
Alex doesn't think this is true. Might be the environment we tested it on. Perhaps it does work for 3.3, etc. Need more testing.

**Comment by CnlPepper** [comment]
Confirmed working with Python 3.3 and Cython 0.27.
