### ISSUE TITLE
triangulate2d doesn't work with closed polygons

### ISSUE THREAD

**Issue by mattngc** [raysect/source#203]
The triangulate2d function takes a ndarray of polygon points and triangulates them using an ear splitting algorithm. As implemented, this function does not allow any points to be coincident, **including** the start and end point. Therefore the array given to this function needs to be an open polygon. This should be more explicit in the documentation for the function.

**Comment by CnlPepper** [comment]
Strictly the triangulate2d function takes a list of polygon vertices with which it constructs a closed polygon. These must be unique and define a simple polygon when connected in sequence.
