### ISSUE TITLE
Noise threshold for 0D observers?

### ISSUE THREAD

**Issue by mattngc** [raysect/source#243]
We currently have 2D frame samplers for setting the noise threshold and controlling the accuracy level for 2D pipelines. Unfortunately there is no equivalent yet for the 0D observers.

**Comment by CnlPepper** [comment]
This was intentional as a 0D pipeline error can be tricially checked, unlike a frame. A typical evaluation loop would simply be:

while pipeline.error > threshold:
    observer.observe(samples=1000)
