### ISSUE TITLE
Get obect from a raysect.optical.loggingray.LoggingRay log

### ISSUE THREAD

**Issue by Mateasek** [raysect/source#250]
Is there any way how to get object for the hits returned by LoggingRay? If not, it could be a nice enhancement for the LoggingRay to return both the coordinates of the interesction of a ray with an object and the object itself.

**Comment by CnlPepper** [comment]
We should just switch it to store the intersection object itself, it would use a bit more memory (~10x) but would be more flexible.

**Comment by mattngc** [comment]
This has now been fixed in the above commits. You can start using this functionality in the latest development branch or wait till merge with master.
