### ISSUE TITLE
Cone or subtract segfaulting

### ISSUE THREAD

**Issue by Mateasek** [raysect/source#251]
Following code appears to segfault:

`cylinder1 = Cone(radius=0.565,height = 0.01, transform =translate(0, 0, -0.005))
cylinder2 = Cone(radius=0.555,height = 0.02, transform =translate(0, 0, -0.01))

radiator = Subtract(cylinder1, cylinder2, parent = world, material=UnityVolumeEmitter())`

**Comment by CnlPepper** [comment]
I suspect a bug may have crept in to Subtract during the last set of changes. Which version of raysect is installed?

**Comment by CnlPepper** [comment]
I've tested this and have been unable to replicate the issue. Could you try rebuilding the code using:

```
dev/build.sh --force
```
in the raysect root folder?

**Comment by CnlPepper** [comment]
hmm, I can't replicate it so far. Could you try running the csg.py demo? If that fails then it is probably a local installation issue. It might be worth updating cython to the latest version and try dev/clean.sh and dev/build.sh.

**Comment by CnlPepper** [comment]
Hi @Mateasek, I've recreated the problem. Will look into it asap.

**Comment by CnlPepper** [comment]
Ok it is crashing in the UnityVolumeEmitter(). I am curious why you are trying to use a volume emitter with an object that has no volume (a plane). Probably why we have no spotted an issue before. It shouldn't segfault though and I am mystified why are this stage. I'll investigate next time we work on raysect.

**Comment by Mateasek** [comment]
Well I was using volume emitter because I am newbie and I was playing around :-)

Anyway I'm happy you have Isolated the reason. Good luck with fixing it!

**Comment by CnlPepper** [comment]
Ok got it, found the issue. Unfortunately it is something we cannot fix easily... I'll need to think about it (though tbh it is an extreme corner case that was only found by making a mistake in the scene setup - using infinite planes).

A pure volume material has no surface, but in the raytracer implementation there is a primitive surface bounding the volume and we therefore need to skip it. The pure volume therefore materials re-fire the ray from the other side of the primitive surface and reduces the ray depth count by 1 so it appears that the surface is not there. Unfortunately if there are two coincident geometric surfaces (as is the case if you subtract an infinite plane from a volume), there is a chance of either surface being intersected with first. One of those surface will be labelled as an "exterior surface". If this surface is intersected first (purely chance), the ray is moved in the wrong direction and will keep re-intersecting the surface again and again until the stack is exceeded.

I'll see if I can find a mitigation just for robustness, but for now, don't subtract infinite planes form a volume - it basically does nothing anyway! ;) :)

**Comment by CnlPepper** [comment]
So your code should not have the last two stages:

radiation = UniformVolumeEmitter(emission_spectrum=ConstantSF(1.0), scale=1.5e5)
radiator = Subtract(cylinder1, cylinder2)

The other line literally do nothing but break the code.
