### ISSUE TITLE
Extract origin/direction from VectorCamera

### ISSUE THREAD

**Issue by shenders** [raysect/source#252]
@mattngc 

The VectorCamera class does not return the input pixel origin/direction which could be a useful output when using the data from VectorCamera at a different stage in the code. Could these two variables be added to the class such that:

camera=VectorCamera(pixel_origin,pixel_direction)

print(camera.pixel_origin,camera.pixel_direction)

**Comment by mattngc** [comment]
This sounds like a sensible change. I will make the respective properties readonly.
