### ISSUE TITLE
Iterating over a node should yield the children?

### ISSUE THREAD

**Issue by mattngc** [raysect/source#273]
Intuitively I expected iterating over a Node object to yield the children. But seems this behaviour is currently not supported. @CnlPepper, is this a behaviour improvement you would support? Maybe you woudn't want to do this in case the deriving class wants to implement its own type of iteration?

**Comment by CnlPepper** [comment]
@mattngc For the reason you identifiedit would not be a good idea to iterate over the node's children from the node object itself, especially as it is pretty trivial to type:

```
for x in node.children:
    blah....
```
instead of:
```
for x in node:
    blah....
```
It is better to leave this free for subclasses to use.
