### ISSUE TITLE
Validate number of positional arguments in FunctionXDs

### ISSUE THREAD

**Issue by mattngc** [raysect/source#274]
The current behaviour of the autowrap function is slightly flawed. Let's say you incorrectly call the `autowrap_function3d()` with a `function2d()`. It can correctly identify that a given function is not a Function3D, but then wraps it in a PythonFunction3D. This leads to an error later down stream when it gets called with the incorrect number of arguments.

An improvement would be to check the number of positional arguments in the __init__() of each PythonFunction*D with the inspect module. For example:

```
>>> from inspect import signature
>>> 
>>> def someMethod(self, arg1, kwarg1=None):
...     pass
>>> sig = signature(someMethod)
>>> sig.parameters
mappingproxy(OrderedDict([('self', <Parameter "self">), ('arg1', <Parameter "arg1">), ('kwarg1', <Parameter "kwarg1=None">)]))
>>> len(sig.parameters)
3
>>> for param in sig.parameters.values():
...     if (param.kind == param.POSITIONAL_OR_KEYWORD):
...         print('Param:', param)
... 
Param: self
Param: arg1
Param: kwarg1=None
```

**Comment by CnlPepper** [comment]
Not sure I'd describe it as flawed, it just allows people to hang themselves - they will get an error message, though it may not be as descriptive as it could be. I'll implement these changes now and get you to review them with your test case.

**Comment by CnlPepper** [comment]
I just tried it out, it sadly proved to myself it won't work reliably. The signature inspection does not work with builtin (c/cython) functions:

```
ValueError: callable <raysect.core.math.function.function3d.Function3D object at 0x7f58a8cb4ba0> is not supported by signature
```
It would break if users supplied usable 3D functions but had default values in the additional dimensions. As such I'm going to label it as wontfix.
