### ISSUE TITLE
Long imports on some core math functions

### ISSUE THREAD

**Issue by mattngc** [raysect/source#283]
Some of the core math functions have very long import paths. Maybe if they are obscure this is fine, but there are a few that I think should be at least brought up to raysect.core.math. From example

from raysect.core.math.function.function1d import PythonFunction1D

**Comment by jacklovell** [comment]
From reading the documentation, it looks like `PythonFunction1D` etc. aren't meant to be called by user code: they're really internal wrappers which should be produced by `autowrap_function1d` etc. Users should only ever need to use `Function1D` instances or Python callables: the wrapping should be handled in Cython by functions which really need a `Function1D` object by using `autowrap_function1d`. So I can understand the autowrap functions having shorter cimports but I don't think the PythonFunction family need to be brought up.

The autowrap functions are currently at `raysect.core.math.function.autowrap_functionxd`. They could be brought up one level, but that would only save 9 characters of typing...

**Comment by CnlPepper** [comment]
@jacklovell is correct here, people are not meant to use PythonFunction1D, it's internal. I think I may rename them to _PythonFunctionXD to make this more obvious.
