### ISSUE TITLE
Planck emmiter 

### ISSUE THREAD

**Issue by Mateasek** [raysect/source#293]
It would be very useful if there was a possibility to add a material contributing with Planck emission to model influence of surface temperature on collected spectra. Maybe @mattngc could have a quick look at it?

**Comment by mattngc** [comment]
There is a black body spectral function here. Unfortunately its currently undocumented :(
Will need to fix that separately.

https://github.com/raysect/source/blob/master/raysect/optical/library/spectra/blackbody.pyx

In reality you need a new material though because its both emitting and reflecting. I don't think you can use the new Blend material for this because its not 50% reflecting metal and 50% a black body emitter, it is simultaneously both of these things.

@ssilburn did some work on this and generously donated the code I've added in commit 4e601fb. There are some caveats though you need to be careful about in the docstring. I would suggest you form a collaboration with Scott at UKAEA if you want to further develop this model.

**Comment by CnlPepper** [comment]
Before this gets committed, I would like to say that this can probably be done in a more general way. The Blend method is indeed not appropriate here as the emission is additive. However baking in a specific spectrum (black body) is also not appropriate. The better approach is to introduce an Add(material1, material2) modifier. It will be up to the user to ensure it is used with appropriate materials. An example usage in this case:

```
hot_beryllium = Add(RoughBeryllium(0.1), BlackBodySurface(500)), surface_only=True)
```

The application to the volume and surface evaluations should be selectable. This feature also needs folding back into Blend.

**Comment by mattngc** [comment]
Yeah, that could be nicer. But might be overkill if we only have one or two instances requiring it. Apart from hot materials I can't think of many materials where you need to chain multiple materials.

**Comment by CnlPepper** [comment]
Well anywhere you want to combine emission with another property this would be useful, not just hot (black body) emission.

**Comment by mattngc** [comment]
ok, I'm fine with this approach.

**Comment by Mateasek** [comment]
@mattngc thanks for pointing me in the right direction. I will test the blackbody radiator you linked. I will also contact Scott, this is something we will need in next few months to support design of overview cameras for COMPASS Upgrade.

I also like the idea of the possibility to add together effects of multiple materials.

**Comment by CnlPepper** [comment]
I'll fold in Scott's code into the black body spectral function, ie add the emissivity fn.

**Comment by mattngc** [comment]
Yeah, those two belong together really.

**Comment by CnlPepper** [comment]
Seems to be working nicely. Just need to wrap up the docstrings and finish the demo render and I'll submit a merge request.

![demo_add_16](https://user-images.githubusercontent.com/8628770/64914517-73648f80-d74b-11e9-9350-0ccdeb9d9b0a.png)

**Comment by CnlPepper** [comment]
That said, the glass example here is double counting the black body emission as I set the surface to emit, not the volume... and there is a front and back surface. I would need to switch to a volume. Need to think about that implementation a bit.

**Comment by CnlPepper** [comment]
As I've said to @mattngc a few times, I'd like to eventually merge the rough (and eventually hot) versions of the materials together. The zero roughness is then just an internal specialism in the model.

**Comment by CnlPepper** [comment]
The code, demo and documentation have been merged into development. Hopefully this should provide a useful interim solution @Mateasek. We can look into developing more accurate hot conductor and dielectric models in the future (where the sensitivity is correctly derived from the absorption).
