### ISSUE TITLE
Identity functions

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#311]
This is another suggestion from #305.

I think we need a function which just returns its input (like the `Identity1D` function proposed in https://github.com/raysect/source/issues/309#issuecomment-543070077). This is needed for any of the function classes where the argument is just a scalar such as `exp(x)` or `sin(x)` but which would otherwise only take functions as arguments.

```python
cdef class Identity1D(Function1D):
    cdef double evaluate(double x):
        return x
```

I suppose you could also have a higher dimensional `Identity` argument where the user chooses which dimension to return during initialisation. Something like this:
```python
cdef class Identity3D(Function3D):
    cdef int dim
    def __init__(self, int dim):
        # Assert 0 <= dim <= 2
        self.dim = dim
    cdef double evaluate(self, x, y, z):
        if self.dim == 0: return x
        if self.dim == 1: return y
        if self.dim == 2: return z
```

More thinking out loud: perhaps replacing dim=0, 1, 2 with dim='x', 'y', 'z' would help readability. These could then be mapped internally to ENUMs to decide which dimension value to return.

You could  then build e.g. a bivariate normal using:
```python
BVGauss = (2 / pi) * Exp2D(-(Identity2D('x')**2 + Identity2D('y')**2))
```
which would evaluate to
```
BVGauss(x, y) == 2 / pi * exp(-(x**2 + y**2))
```

**Comment by mattngc** [comment]
This also sounds really cool to me. I would really like to see a lot of the math library expanded in Raysect. And eventually... the core math library could be spun out into a separate clean package or contributed to scipy, etc. The math functions are generally useful to everybody, not just ray tracing people.
