### ISSUE TITLE
Unexpected autowrap behaviour for FunctionxD special methods

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#325]
I noticed that the `AddFunctionxD` etc. classes in `base` autowrap function arguments, but this currently doesn't seem to have any effect. These classes are not public, and so will only be instantiated by calling `FunctionxD.__add__`  etc. However, this special method will only create `AddFunctionxD` if its arguments are already `FunctionxD` instances, in which case autowrapping becomes a noop.

This also means that currently it's not possible to add a `FunctionxD` to a Python callable:
```python
from raysect.core.math.function import Arg2D
def f(x, y): 
    return x + y
g = Arg2D('x')
h = f + g
f + g
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'function' and 'raysect.core.math.function.function2d.arg.Arg2D'
```

Do we want raysect to support the above use case? It seems to me it would be useful. In this case, the `autowrap_functionxd` calls should be moved from the `AddFunctionxD` etc. classes into the `__add__` etc. methods of `FunctionxD`, along with a check that the object is callable.

If this isn't going to be supported by raysect, then the autowrap functions can be removed entirely from base.pyx. Which would have the nice side effect of removing a circular import.

**Comment by CnlPepper** [comment]
We could add python function support to the special methods and add autowrapping as required. Should be a simple case of checking if the object is callable.

I think addressed the circular import by moving the autowrap functions out of the base to sit with the PyhonFunctions wrappers, where they belong.

**Comment by jacklovell** [comment]
At the moment, base.pyx `cimport`s from autowrap.pyx for the autowrap functions, and autowrap.pyx `cimport`s from base.pyx for the `FunctionxD` class. I agree that autowrap belongs with the `PythonFunction` class, but I don't see how this avoids a circular import (or indeed, how it would be possible to avoid a circular import by using autowrap in base.pyx).

An `if callable()` check for wrapping any callable Python object in the arithmetic methods sounds like it would be very useful. Presumably it would be up to the end user to ensure that the callable they pass matches the signature of a `FunctionxD`?

If you're happy to keep autowrap calls in base then we should move the autowrap calls from `AddFunction` etc. into the `__add__` etc. methods. I'm happy to contribute this.

**Comment by CnlPepper** [comment]
Ah ok just figured out my confusion when you said circular imports. There is no circular imports in the .pxd files (where it matters). The implementation files can all reference each other, the resolution is done after compilation in the linking stage.

All we have to do is change the AddFunctionXD init to accept object types. It ***should*** have been already been accepting objects as the autowrap is pointless if arbitrary objects can't be passed! That was a bug that we never encountered until now.

Then we just all all the callable() if statements.

I'll test it out and make sure it work with the arguments either way round.... it should if the other object returns NotImplemented correctly if it can't handle a type.

**Comment by CnlPepper** [comment]
Just tested it, it works as expected. I'll make the changes and make a merge request for you to test.

```
In [9]: c = Constant1D(60)
In [10]: a = c + (lambda x: x*2)                                                                                                                                                                                                                               
In [11]: b = (lambda x: x*2) + c

In [12]: a(2)                                                                                                                                                                                                                                                  
Out[12]: 64.0

In [13]: b(5)                                                                                                                                                                                                                                                  
Out[13]: 70.0
```

**Comment by CnlPepper** [comment]
@jacklovell I've implemented the required changes for all the FunctionXD classes. Could you please test them out and confirm they fix the issue for you? If they do, I'll merge the code.

**Comment by CnlPepper** [comment]
Fixes merged into development.
