### ISSUE TITLE
Multicore engine gives different result to serial engine when the order matters

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#328]
I have a simple case where I'm using a render engine to perform a calculation and append the results to a list. The result from the serial engine is what I expect (it matches that of a list comprehension), whereas the results from the Multicore engine are reversed:

```python
from raysect.core.workflow import SerialEngine, MulticoreEngine


def calculator(task):
    print(task)
    i, j = task
    return i * j


tasks = [(i, j) for i in range(1, 4) for j in range(10, 14)]
serial_engine = SerialEngine()
serial_results = []
serial_engine.run(tasks, calculator, serial_results.append)
print(serial_results)
parallel_results = []
parallel_engine = MulticoreEngine()
parallel_engine.run(tasks, calculator, parallel_results.append)
print(parallel_results)
```
Output:
```
(1, 10)
(1, 11)
(1, 12)
(1, 13)
(2, 10)
(2, 11)
(2, 12)
(2, 13)
(3, 10)
(3, 11)
(3, 12)
(3, 13)
[10, 11, 12, 13, 20, 22, 24, 26, 30, 33, 36, 39]
(3, 13)
(3, 12)
(3, 11)
(3, 10)
(2, 13)
(2, 12)
(2, 11)
(2, 10)
(1, 13)
(1, 12)
(1, 11)
(1, 10)
[39, 36, 33, 30, 26, 24, 22, 20, 13, 12, 11, 10]
```
It's also clear from the output that the tasks are being called in reverse order for the Multicore engine.

The documentation for the base `RenderEngine` class states "This class provides a rendering workflow that abstracts away the underlying system performing the work." As such, the results should be independent of the engine performing the work.

Looking through workflow.py, it seems the culprit is the `jobs.append(tasks.pop())` line in `MulticoreEngine._producer`. Tasks are put into the job queue from the back of the task list, whereas in the serial engine they're called from the front of the queue. A simple fix would be to make `tasks` a `collections.deque` object and then use `tasks.popleft` to add tasks to each job. Would you be happy with this change?

As an aside, the `if __name__ == "__main__"` section in workflow.py is broken. Doing `from time import time` and overwriting the name time from `import time` at the top of the file seems to break stuff.

**Comment by CnlPepper** [comment]
The render engines treat each task as independent, the order of the tasks is not guaranteed. The ordering is not guaranteed even with your change if the amount of work differs for each task. If you need a specific ordering, an id should be added to the task so the results can be resorted. The observers send a pixel id with each task for example.

**Comment by jacklovell** [comment]
Ah, OK. This isn't clear from the documentation: any chance you could add a sentence explicitly saying that the order in which tasks are run is not guaranteed?

**Comment by CnlPepper** [comment]
Yeah that would probably be a good idea, I'll do that tonight.
