### ISSUE TITLE
Changing 'pixels' parameter in some 2D observers does not update image geometry.

### ISSUE THREAD

**Issue by vsnever** [raysect/source#333]
Setting `pixels` parameter in `PinholeCamera` and `OrthographicCamera` after initialisation must trigger a call to `_update_image_geometry()` just like in `CCDArray`. However, the default setter from the parent class is not overridden here, so the image geometry will not be updated.

Setting `pixels` parameter in `VectorCamera` must not be allowed at all. Now it is possible via the default setter from the parent class. It's unlikely that someone will try but maybe a warning should be raised if this happens?
```
@pixels.setter
def pixels(self, value):
    warnings.warn("Setting 'pixels' parameter is not allowed in VectorCamera")
```

**Comment by mattngc** [comment]
Thanks Vlad, good catch. Indeed, it is a bug.

**Comment by CnlPepper** [comment]
Curious, I thought I fixed that. I must have forgotten to merge it.  The vector camera needs bit of tiding up, it was originally quickly cobbled together to address a specific use case.
