### ISSUE TITLE
Regarding the Fresnel term

### ISSUE THREAD

**Issue by munechika-koyo** [raysect/source#341]
Hello, 
I just would like to know about the Fresnel term on microfacet model in raysect.
According to the published paper: https://aip.scitation.org/doi/10.1063/1.5092781, I understand that the Fresnel term depends on the both of refractive index and extinction coef (and also incident angle?). But, how much range of energy (i.e. wavelength) is given to this term?

I would like to use the raysect for developing Infrared Viewing Bolometer, and also consider the effect of wall reflection. So, I just wonder about that because bolometers can capture not only visible light but all of the other lights.

Thank you in advance for your cooperation.

**Comment by mattngc** [comment]
Hi @munechika-koyo,

The relevant code you are looking for is here in between lines 77 - 133.
https://github.com/raysect/source/blob/4f68105892ae410052f1e1338e025f376f79e2ce/raysect/optical/material/conductor.pyx#L77

Raysect samples the material reflection properties according to the wavelength range and resolution specified by the user. When you set up an observer you typically specify these settings on the observer. On the observer base class there are these parameters for example:

- spectral_bins (int) – The number of spectral samples over the wavelength range (default=15)
- min_wavelength (float) – Lower wavelength bound for sampled spectral range (default=375nm)
- max_wavelength (float) – Upper wavelength bound for sampled spectral range (default=740nm)
(https://raysect.github.io/documentation/api_reference/optical/observers.html#raysect.optical.observer.base.observer._ObserverBase)

So with these default settings the wavelength range 375nm - 740nm would be split up into 15 equal length wavelength bins. For each of these bins:

1. The central wavelength of each bin is calculated
2. The n, k values for the material in question are sampled at the central wavelength
3. The Fresnel term is evaluated at this central wavelength
4. The resulting reflectivity is effectively treated as flat over this wavelength bin and integrated.

So in your case you would need to consider a number of things.
- The wavelength range over which your bolometer is sensitive. You need to provide experimental or theoretical n, k wavelength data for your materials.
- What wavelength range is safe to integrate over? For some metals n and k are basically flat over the visible. So in these cases you could use a wide wavelength bin in the interests of speed. But if you have a gradient in n+k you will get missleading results. Equally if you have a gradient in the wavelength response of your plasma source then you will also get missleading results.

Raysect has been designed to support arbitrary wavelength ranges as long as you can provide data for the material and the source function. But you will need to choose the integration settings appropriately. If you need non-uniform sampling over wavelength you could break up the problem into a number of wavelength regions and then integrate them all manually at the end.

**Comment by CnlPepper** [comment]
The refractive index and extinction functions are user definable to an arbitrary wavelength range.  For the metals we use interpolated, tabulated data. See here for the raw data:

https://github.com/raysect/source/tree/master/raysect/optical/library/metal/data

You can define "SpectralFunctions" from your own data and instance your own RoughConductor. Please see: https://raysect.github.io/documentation/api_reference/optical/main_optical_classes.html#raysect.optical.spectralfunction.InterpolatedSF

**Comment by munechika-koyo** [comment]
Thank you for answering my question!
I understood how to apply n, k values to a material object.
I have the plasma radiation profile data [W/m^3] in each photon energy [J].
So, I would like to use it as a emitter, and set the range of wavelength referring to this profile.

Thank you so much and please let me ask you if I am worried about something again.

**Comment by mattngc** [comment]
Thanks @munechika-koyo, just create a new question if you need help again. Regards, Matt
