### ISSUE TITLE
Regarding the fresnel term on (Rough)Conductive material

### ISSUE THREAD

**Issue by munechika-koyo** [raysect/source#352]
Hello.

I have a question regarding the fresnel term, which is coded in the conductor.pyx: 
file:https://github.com/raysect/source/blob/0973260f115212aa954ad103080f465ffed78a11/raysect/optical/material/conductor.pyx#L136

I can understand the one which is coded in the dielectric.pyx, but I am wondering why the conductive's fresnel term is such a simple form.
I would appreciate it if you could tell me how to derive this term or which reference you referred to. 

Sorry for my basic question, and thank you in advance.
Best regards,

Koyo

**Comment by munechika-koyo** [comment]
Sorry for my late reply.
I also tried to derive the Fresnel reflectivity which is coded in raysect using the standard fresnel reflectance coefficient:

![image](https://user-images.githubusercontent.com/51052381/78135641-30ef6f80-745d-11ea-827a-293ba5c6f5b1.png)

This is the s-polarized light's reflectance coefficient.
And, assuming that light waves travel through a vacuum and hit the conductive material, the complex refractive index of which is n_hat, r_s is represented by as follows:

![image](https://user-images.githubusercontent.com/51052381/78137158-c855c200-745f-11ea-8963-72e2ca9e6b51.png)

So, I tried to take the absolute value of this equation (|r_s|^2 = (r_s) x (r_s)*) and derive the raysect's s-paralyzed reflectivity form, but I don't have any idea how to transform it.

And the raysect's form seems to be more simple form than the original one.
Did you apply any approximation to that?

I would appreciate it if you could give me a little hint on that.

**Comment by CnlPepper** [comment]
I can't find my derivation unfortunately. If I remember correctly, when you substitute the complex refractive index into the full unpolarised light (parallel + perpendicular polarisation) reflectance equation, many of the terms end up cancelling.

**Comment by CnlPepper** [comment]
I've had a dig into this a bit more, there is infact an approximation in the raysect equation. It's a common one for dielectric-conductor interfaces. See the following for a good write up. The approximation is described.

https://seblagarde.wordpress.com/2013/04/29/memo-on-fresnel-equations/

I'm tempted to switch to also include the full equation now you've brought this to my attention.

**Comment by munechika-koyo** [comment]
thank you @CnlPepper 
the approximation which you told me was very useful for me to understand how the fresnel term is calculated.
And I am sorry not to replying sooner.

**Comment by CnlPepper** [comment]
No worries, happy it was helpful. :)
