### ISSUE TITLE
BiConvex and Meniscus lens construction fails for large centre_thickness

### ISSUE THREAD

**Issue by Mateasek** [raysect/source#354]
While putting together tests for lens primitives I discovered another issue. The construction for large center_thickness parameter can produce lenses of wrong shape or even no shape at all, see in the picture. The left column are menisus lenses, the right contains biconvex lenses. The centre_thicknes parameter is increasing from top to bottom. The increase causes the meniscus lense to have wrong position and shape of a biconvex lens. The biconvex lens has wrong position and decreasing diameter up to a point when it "dissapears".

![lens_fail](https://user-images.githubusercontent.com/969455/77551731-fc0a7800-6eb2-11ea-8423-6c19e7a4e910.png)

The lenses were generated using this code:
``` python
BiConvex(diameter, 0.015, 0.02, 0.02, parent=world, transform=translate(1.7 * diameter, 0, 0), material=schott("N-BK7"))
BiConvex(diameter, 0.03, 0.02, 0.02, parent=world, transform=translate(0.6 * diameter, 0, 0), material=schott("N-BK7"))
BiConvex(diameter, 0.075, 0.02, 0.02, parent=world, transform=translate(-0.6 * diameter, 0, 0), material=schott("N-BK7"))
BiConvex(diameter, 0.1, 0.02, 0.02, parent=world, transform=translate(-1.7 * diameter, 0, 0), material=schott("N-BK7"))

Meniscus(diameter, 0.015, 0.02, 0.02, parent=world, transform=translate(1.7 * diameter, 0, -0.1), material=schott("N-BK7"))
Meniscus(diameter, 0.03, 0.02, 0.02, parent=world, transform=translate(0.6 * diameter, 0, -0.1), material=schott("N-BK7"))
Meniscus(diameter, 0.075, 0.02, 0.02, parent=world, transform=translate(-0.6 * diameter, 0, -0.1), material=schott("N-BK7"))
Meniscus(diameter, 0.1, 0.02, 0.02, parent=world, transform=translate(-1.7 * diameter, 0, -0.1), material=schott("N-BK7"))
```

This is in my opinion caused by way lens objects are constructed with CSG. In both cases ([BoConvex](https://github.com/raysect/source/blob/0973260f115212aa954ad103080f465ffed78a11/raysect/primitive/lens/spherical.pyx#L114), [Meniscus](https://github.com/raysect/source/blob/0973260f115212aa954ad103080f465ffed78a11/raysect/primitive/lens/spherical.pyx#L466)) the procedure is first intersection of the front and back spheres and then intersection of the result with the barrel. This fails when the distance of the sphere centers gets too large due to the center_thickness parameter.

I know these examples are not probably relevant for any realistic lenses, but I think this behaviour should not be allowed. I see two solutions:

1. add upper limit to the center_thickness parameters
2. change the lens construction procedure from the primitive shapes

I can combine a fix for this issue into a PR with tests I've been working on. I would personaly prefer the second option.

**Comment by CnlPepper** [comment]
Interesting. Yes you are right the build order was never intended to cope with hugely thick lenses.

I think we may need to intersect the front and back spheres with a cylinder to cut off the spherical caps. Then union these with the barrel. I'd be very worried about numerical accuracy issues though.
This will take some thought.

**Comment by Mateasek** [comment]
The issue with convex surfaces could be solved by intersecting surface spheres with a cylinder, which is extending beyond the lens body. This could work and is as simple as what is used now.

**Comment by Mateasek** [comment]
I probably should stop posting comments late in the evening... You are right that this needs a thought, the poposed pocedure was also not handling thick lens correctly also. The best idea I have now is adding a second barrel stretching between the curvature centers to cover the center thickness , but how would that behave when the curvature and lens diameters were the same?

**Comment by Mateasek** [comment]
After some time I think introducing an upper threshold to center thickness could be a good option. It could either stop the lens init completely and we could add extra classes for thick spherical lenses or it could be used to switch to construction suitable for thick lens. This way the current simple and efficient construction would be kept and probably used in most of the applications while keeping the thick lens option.

**Comment by Mateasek** [comment]
I've implemented different construction for thin and thick lens cases into Planoconvex (1,2 from top), BiConvex (3, 4 from top) and Meniscus (5, 6 top) lenses. It still has to be checked, but looks promissing. The threshold for the thin (current construction) to be used is the maximum venter thickness it stilll works for. I have to tests still, but looks promissing by eye-metrics.

![lens_render](https://user-images.githubusercontent.com/969455/77675369-2597d200-6f8d-11ea-9436-827001e4086a.png)

**Comment by CnlPepper** [comment]
If you have a PR, I'll take a look.

**Comment by mattngc** [comment]
Just curious, is it ever practical to have such thick lenses? I would have thought such thick lenses have very little physical relevance even if it is a legitimate bug.

**Comment by Mateasek** [comment]
I would be worried about the fact that biconvex, planoconvex and menisucs lenses can behave in very unpredictive way.

I made a draft PR  #355  to show what I've done so far. The only lens not finished is the meniscus, which has some problems close to the edges of the back surface. I will change the structure of the unittest class to introduce more versatility to the methods for surface testing, which might solve the issue.

The problem is that even though the ray is shot towards the edge of the lense, it misses. I have to investigate if it is an error in the construction or problem of the ray or just numerics.

**Comment by Mateasek** [comment]
I think I am done from my part. The new way of lens construction and tests are in PR #355.
