### ISSUE TITLE
Interpolators require very long import string in Cython files

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#360]
The `Discrete2DMesh` and `Interpolate2DMesh` interpolators can't be `cimport`ed from `raysect.core.math.function.float`. Instead, they need to be imported from `raysect.core.math.function.float.function2d.interpolators`, which seems unnecessarily verbose. Would it be a good idea to include them in the `float` namespace, along with all the other `float` function objects? This is already possible from Python, just not cython.

It looks like this is just because `raysect/core/math/function/float/function2d/__init__.pxd` is missing the `from interpolators cimport *` line which the corresponding `__init__.py` file already has.

**Comment by CnlPepper** [comment]
You are right, looks like I missed this import. I'll fix it now.
