### ISSUE TITLE
Vector functions require long imports in Cython

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#361]
Similar to #360, the `vector3d` function objects require very long Cython imports because the base classes are missing from the `__init.pxd__` files in  functionxd.

The python imports have a nice symmetry between `float` and `vector3d`: the same should be true of the cython imports.

For example:
```python
from raysect.core.math.function.float cimport Function1D, autowrap_function1d
from raysect.core.math.function.vector3d.function1d.base cimport Function1D
from raysect.core.math.function.vector3d.function1d.autowrap cimport autowrap_function1d
```

Should be:
```python
from raysect.core.math.function.vector3d cimport Function1D, autowrap_function1d
```

**Comment by CnlPepper** [comment]
Thanks for the PR.
