### ISSUE TITLE
Wrong construction of PlanoConvex lens

### ISSUE THREAD

**Issue by Mateasek** [raysect/source#363]
PlanoConvex lens is [constructed](https://github.com/raysect/source/blob/0140eca403eaff44f96e5c6f07cdf85efe514498/raysect/primitive/lens/spherical.pyx#L285-L290) in a wrong way. The barrel is too short to form a lens in intersection. I can quickly push a fix, but I would be happier if somebody could look at the PR #355 which also fixes this problem.

**Comment by CnlPepper** [comment]
I think that would only be true for very small radius, long barrel lenses. I'll have a look at the PR when I get a spare moment. The solution would be to union a cylinder of the required length before the intersection.

**Comment by Mateasek** [comment]
I discovered it when I was trying to benchmark model of one of our objectives, so it is definitely happening for realistic lenses.

**Comment by CnlPepper** [comment]
Apologies for not tackling your pull requests, most of the items you have been working on require me to sit down and think carefully. Unfortunately I'm only got the capacity for minor quick fixes at the moment, or mindless restructuring work. I will get to these and I am grateful for them. The new company is drawing most of my cognitive time. It should get easier over the coming months.
