### ISSUE TITLE
Raysect needs a logo

### ISSUE THREAD

**Issue by mattngc** [raysect/source#37]
Raysect needs a proper logo. Then this logo can be used in the documentation pages and on github, etc.

**Comment by CnlPepper** [comment]
See feature/raysect_logo

**Comment by CnlPepper** [comment]
New logo has been added:
![raysectlogo_small](https://cloud.githubusercontent.com/assets/8628770/9294663/12afc2a4-444c-11e5-818e-67845c7c8f32.png)
