### ISSUE TITLE
Support multiprocessing in Python 3.8+ in macOS

### ISSUE THREAD

**Issue by vsnever** [raysect/source#375]
Starting with Python 3.8, 'spawn' is a default method for starting a child process in multiprocessing module under macOS. This breaks Raysect's installation and makes multi-core rendering almost unusable because of memory consumption. However, the 'fork' method can still be used. It is possible to continue to use multiprocessing in Raysect under macOS by patching `MulticoreEngine` and setup.py.

This patch makes Raysect work fine in macOS (tested in 11.2 Big Sur with Python 3.8.8) and does not change its behaviour in Linux: https://github.com/vsnever/raysect-source/commit/ec563efc7c2739a45f3e3dba246a951589748c5f.

@CnlPepper, if you are happy with this patch, I'll make a PR. As a Mac user (kind of), I would like to keep macOS support in Raysect.

**Comment by CnlPepper** [comment]
We don't officially support MacOS, but trivial changes to enable support should be ok.

I am a bit confused by your patch though, shouldn't simply setting the process start method be enough? Why do you need to use the context explicitly?

I also don't understand what the setting in setup.py is doing either, that only runs during install.

**Comment by CnlPepper** [comment]
Nevermind, I had a look through the multiprocessing docs. I understand the changes now. Please make a PR.

**Comment by vsnever** [comment]
Without that patch in setup.py, the installation will fail just like in https://github.com/cherab/core/issues/223.
> Nevermind, I had a look through the multiprocessing docs. I understand the changes now. Please make a PR.

Ok, I'll do.
