### ISSUE TITLE
raysect.org doesn't support https

### ISSUE THREAD

**Issue by dschwoerer** [raysect/source#398]
This breaks linking for external projects (like https://github.com/cherab/core/issues/314) but also from within github with extensions like https everywhere.

https://letsencrypt.org/ could be used to get certificates. Please let me know if there is something I can do to help.

PS: I would have reported this at https://github.com/raysect/documentation but the issue tracker there is disabled ...

**Comment by CnlPepper** [comment]
I've reconfigured github pages and the domain DNS. HTTPS should now be supported. The URL is now cleaner too as github redirects to raysect.org domain. Could you check it is working for you? If so, I'll close the issue.

**Comment by dschwoerer** [comment]
Thanks, much nicer now :+1:
