### ISSUE TITLE
Installation from sdist on PyPI fails if cython and numpy are not already installed

### ISSUE THREAD

**Issue by jacklovell** [raysect/source#401]
On Python 3.6 and 3.10, where binary wheels of raysect 0.7.1 are not available on PyPI and the sdist is instead used, running `pip install raysect==0.7.1` in a fresh virtual environment fails. This is because cython and numpy are dependencies of setup.py, but pip doesn't know this until it tries to run setup.py to get the project dependencies.

In Cherab we had a similar issue and fixed it by adding a pyproject.toml file conforming to PEP517. Doing the same for raysect would further simplify the installation procedure for new users.

**Comment by CnlPepper** [comment]
Merged for release 0.7.2.
