### ISSUE TITLE
The 'quiet' argument passed to Observer1D and Observer2D at initialisation is ignored.

### ISSUE THREAD

**Issue by vsnever** [raysect/source#408]
The `quiet` argument passed to `Observer1D` and `Observer2D` at initialisation is not passed to the `_ObserverBase` initialiser.

`Observer1D`:
https://github.com/raysect/source/blob/d8b7903abd65e1d651fc280dad7f3e20454224a3/raysect/optical/observer/base/observer.pyx#L732-L746

`Observer2D`:
https://github.com/raysect/source/blob/d8b7903abd65e1d651fc280dad7f3e20454224a3/raysect/optical/observer/base/observer.pyx#L911-L925

**Comment by CnlPepper** [comment]
Fixed in development. Will be released in v0.8.1.
