### ISSUE TITLE
Proposal: material library update

### ISSUE THREAD

**Issue by wave46** [raysect/source#410]
Dear Raysect team.

As I can see from the data stored for metals refractive index and extinction coefficients, their wavelength range is from 200 nm to 12.4 mkm. However for tokamak VUV diagnostics I'd like to have optical properties of the metals to be resolved for lower wavelengths.
Also, I noticed that, for example, [here](https://refractiveindex.info/?shelf=main&book=W&page=Werner-DFT) one of the databases goes down to 1.8 nm. I tried to compare data from different sources mentioned there and it seemed to me that they are quite different. Also, they cover different wavelength ranges.

So, I think, this different sources should be somehow merged and put into the Raysect default library. Or, at least, this different sources can be stored and users can choose the one that covers the wavelength range they want.

Thanks,
Ivan Kudashev

**Comment by CnlPepper** [comment]
We advise the user to interpolate their own data with an appropriate spectral function if they want to use an expanded dataset. Raysects library is not intended to cover all use cases.

**Comment by CnlPepper** [comment]
Please see raysect/optical/library/metal/metal.py in the repository to see how to interpolate your own data.
