### ISSUE TITLE
Non-uniform step, absorption & scattering: inhomogeneous.pxd

### ISSUE THREAD

**Issue by MMoscheni** [raysect/source#414]
Hi there, many thanks as usual for the amazing work! Below is our idea of implementation of non-uniform smapling along the ray direction, alongside absorption and scattering. Changes to the original code are marked by "MMM". More insights are provided in [A. Aimetta, M. Moscheni et al, "Forward modelling of Dα camera view in ST40 informed by experimental data", submitted to Fus. Eng and Des.]. If you have any feedbacks on this, that would be appreciated!

    # cython: language_level=3
    
    # Copyright (c) 2014-2021, Dr Alex Meakins, Raysect Project
    # All rights reserved.
    #
    # Redistribution and use in source and binary forms, with or without
    # modification, are permitted provided that the following conditions are met:
    #
    #     1. Redistributions of source code must retain the above copyright notice,
    #        this list of conditions and the following disclaimer.
    #
    #     2. Redistributions in binary form must reproduce the above copyright
    #        notice, this list of conditions and the following disclaimer in the
    #        documentation and/or other materials provided with the distribution.
    #
    #     3. Neither the name of the Raysect Project nor the names of its
    #        contributors may be used to endorse or promote products derived from
    #        this software without specific prior written permission.
    #
    # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    # AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    # ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
    # LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
    # CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    # SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    # INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    # POSSIBILITY OF SUCH DAMAGE.
    
    from raysect.optical cimport World, Primitive, Ray, Spectrum, Point3D, Vector3D, AffineMatrix3D
    from raysect.optical.material.material cimport NullSurface
    
    
    cdef class VolumeIntegrator:
    
        cpdef Spectrum integrate(self, Spectrum spectrum, World world, Ray ray, Primitive primitive,
                                 InhomogeneousVolumeEmitter material, Point3D start_point, Point3D end_point,
                                 AffineMatrix3D world_to_primitive, AffineMatrix3D primitive_to_world)
    
    
    cdef class NumericalIntegrator(VolumeIntegrator):
    
        cdef:
            double _step
            int _min_samples
    
        cdef int _check_dimensions(self, Spectrum spectrum, int bins) except -1
        # MMM
        cdef double _compute_step_sampling(self, InhomogeneousVolumeEmitter material, Point3D point) except -1
        cdef tuple _simulate_scattering(self, InhomogeneousVolumeEmitter material, Point3D point, int num_collisions)
    
    
    cdef class InhomogeneousVolumeEmitter(NullSurface):
    
        cdef public VolumeIntegrator integrator
    
        cpdef Spectrum emission_function(self, Point3D point, Vector3D direction, Spectrum spectrum,
                                         World world, Ray ray, Primitive primitive,
                                         AffineMatrix3D to_local, AffineMatrix3D to_world)

**Comment by CnlPepper** [comment]
Thank you for your work, but his is not an appropriate way of suggesting a code change. Please confine content to a single issue or merge request.
