### ISSUE TITLE
Support initial Interpolator2DMesh

### ISSUE THREAD

**Issue by mattngc** [raysect/source#45]
- many scientific data problems will produce solutions on meshes, i.e. finite element analysis, non-linear PDEs, etc.
1. Allow user to import a mesh with data values attached.
2. kd-tree looks up nearest mesh triangle that contains test point
3. Barycentric Interpolation to get data values at that point.

**Comment by mattngc** [comment]
Hey @CnlPepper 

I'm at my whits end with this bug. I can't work out what is wrong. Please try the following and see if you can work it out:
1. Check out latest version of branch feature/mesh_interpolator.
2. %run demos/mesh_interp/new_meshdata.py
3. I get this error, can't work out what is causing it. Unfortunately it means lines 180-188 of TriangleMeshData.pyx never runs.
Exception ignored in: 'TriangleMeshData._TriangleMeshTriangle.contains'
TypeError: a float is required

**Comment by CnlPepper** [comment]
The error is on line 138. The code is incomplete:

        v1, v2, v3 = self

        v1, v2, v3 = self.v1, self.v2, self.v3

**Comment by mattngc** [comment]
Need to break this code up into smaller test cases. Maybe allow interchangability between brute-force and kd-tree approach. Unfortunately, the scipy kd-tree doesn't seem to work well with this type of problem. A raysect specific kd-tree will be necessary.

**Comment by mattngc** [comment]
Functionality is complete. 2D kd-tree and associated 2D math will be dealt with in other tickets. Currently usable without specialised raysect 2D kd-tree.
