### ISSUE TITLE
Basic mesh primative

### ISSUE THREAD

**Issue by mattngc** [raysect/source#5]
- allow meshes to be used as a primative geometry type
- useful for representing complex geometries, probably CAD generated parts

**Comment by CnlPepper** [comment]
Work has started in the feature/mesh branch.

**Comment by mattngc** [comment]
Raysect now supports meshes.  See c6df80d.
Currently allows users to import a mesh from .obj or .stl and render an image.
Currently slow due to need for kdTree optimisation, but this can be considered a separate ticket (#13).
