### ISSUE TITLE
Support for a basic CAD format

### ISSUE THREAD

**Issue by mattngc** [raysect/source#6]
- pick a CAD format that is open and simple to support
- enable a CAD file in that format to be loaded as a mesh primative

**Comment by CnlPepper** [comment]
Initial support will be for OBJ and/or STL due to the simplicity of the formats. Full solid geometry CAD formats will require significant investment of time.

**Comment by mattngc** [comment]
Found a suitable library for loading/reading .stl files.
https://pypi.python.org/pypi/numpy-stl

**Comment by mattngc** [comment]
Added both ascii and binary versions of the .stl parser.
Now just needs to be merged with Alex's new mesh object.

**Comment by mattngc** [comment]
Alex has also added a .obj parser. Both of these will have to evolve as the mesh objects are developed and kdTree is rewritten. But fundamentally, this ticket has been addressed.
