### ISSUE TITLE
Design a set of component classes for observer construction

### ISSUE THREAD

**Issue by CnlPepper** [raysect/source#61]
It would be useful to have a common set of classes to represent pixels, fibre optic tips etc...

e.g:
 square pixel - launches rays that sample over acceptance cone and pixel surface
 point pixel - launches rays that sample over an acceptance code

Then define a few acceptance cones classes - hemisphere, cone, delta function.

Can then easily build CCD observers etc...

**Comment by mattngc** [comment]
Alex has come up with the design. Matt will implement.

**Comment by mattngc** [comment]
This work is now largely completed. Relevant commit is 1186d551a621a7cefb41fc6e047cad115a0a05f8.

More work will be ongoing. Need to add a few new observers as well as general refactoring and tidying up before merge request. But the core issue is complete.
