### ISSUE TITLE
Cache raysect meshes with generated kd-tree

### ISSUE THREAD

**Issue by mattngc** [raysect/source#63]
Currently it takes a long time to process large meshes. In some cases, it can take as long as an hour to process all the mesh nodes and build the kd-tree. It would make sense to pre-process a mesh and save the python mesh representation with all its acceleration structures into a dedicated raysect mesh file format. This allows users to only process meshes when changes are made to the underlying mesh components. For routine ray-tracing with the same meshes, the meshes can quickly be re-loaded from the raysect mesh files.

**Comment by CnlPepper** [comment]
Added in commit caafb846872bc8e6f20de8263a8bcfeacf8ec002
