### ISSUE TITLE
Create a library module

### ISSUE THREAD

**Issue by CnlPepper** [raysect/source#64]
Create a library module in optical that contains predefined materials, spectra and observers.

Example items for the library:
* glasses from a manufacturer such as schott
* metals such as Gold, Silver, Carbon etc...
* observers that model a real CCD or camera
* spectra and spectral functions such as CIE XYZ curves, black body radiation etc...

The core materials from which these are derived e.g. conductor, dielectric etc... that require data before use will remain in the material folder. Similarly the observer components and generic CCD objects (when created) will remain in observers.

**Comment by mattngc** [comment]
Added in recent commit in lens branch.
