### ISSUE TITLE
add 2D Math classes to the core.math package

### ISSUE THREAD

**Issue by mattngc** [raysect/source#69]
We need 2D math classes for the 2D kd-tree and the MeshInterpolator. Split the existing math classes into 2D and 3D components.

**Comment by CnlPepper** [comment]
Vector, Point, Normal, AffineMatrix and BoundingBox renamed to Vector3D, Point3D, Normal3D, AffineMatrix3D and BoundingBox3D.
Point2D and BoundingBox2D added.

Issue closed by commit 49681ba458bbf63a9ad30273a9ba4fd763b734e6
