### ISSUE TITLE
Emission at a point in world space

### ISSUE THREAD

**Issue by mattngc** [raysect/source#70]
An important use case is the ability to ask for the emission from any given point in the scene. For example:

```python
world.emission(point = Point(x, y, z), direction=Vector(vx, vy, vz))
```

Unfortunately, at the moment it is not possible to ask for the emission at a point without providing a ray as argument.

```python
cpdef Spectrum emission_function(self, Point point, Vector direction, Spectrum spectrum,
                                 World world, Ray ray, Primitive primitive,
                                 AffineMatrix to_local, AffineMatrix to_world):

    raise NotImplementedError("Virtual method emission_function() has not been implemented.")
```
 This sort of functionality could be trivially added if the emission model doesn't need access to the ray itself. Most of the volume emitter classes we have written so far don't require `ray` for their implementation.

**Comment by CnlPepper** [comment]
The emission_function() isn't generally available for all materials. It is only available for the inhomogeneous volume emitter. This functionality is not as trivial to implement in a general way as stated. The requested behaviour would be considered outside the main work flow of the raytracer.

**Comment by mattngc** [comment]
I've been thinking about this. I'm starting to agree with you that it might be best to support this sort of functionality in the users emission model, rather than as a general feature. Its a bit of a shame since it would be a very useful feature to have. But I take your point that it could potentially break the raytracers workflow. I'm going to try it in a user emission model to test the workflow. If it looks possible to include this in raysect, I'll re-open the ticket.
