### ISSUE TITLE
Create render engine object

### ISSUE THREAD

**Issue by mattngc** [raysect/source#81]
Currently cameras have code paths for single and parallel processing. This could be abstracted in to separate 'render' engines.

**Comment by CnlPepper** [comment]
Would like an abstraction that decouples the method of execution from an observers workflow. Must allow the ability to support single process, multi process and cluster rendering. A set of methods should be provided that are used to carve up the render job into tasks, execute those tasks and assemble the final result. The execution of tasks being either single threaded or concurrent.

**Comment by CnlPepper** [comment]
Concurrency drives the design. Basically want a Producer -> Worker(s) -> Consumer scheme.

RenderEngine spawns Producer and Workers, it becomes the Consumer.

* Producer is given a list of work instructions which it sends to the workers
* Workers unpack, execute work task described by instruction and send results to consumer
* Consumer (main process) unpacks task results and merges them into result

Can build the design to be totally general.
* Producer receives a list of objects it passes to worker.
* Worker receives task object and passes it to a user supplied execution kernel. Result object passed on to consumer
* Consumer receives result object and passes to a result processor.

The RenderEngine is initialised by supplying a WorkFlow object which exposes virtual functions for the worker init() and kernel(), and consumer update() methods.
