### ISSUE TITLE
Add methods to intersection to calculate surface space transforms

### ISSUE THREAD

**Issue by CnlPepper** [raysect/source#87]
For some materials (e.g. Lambert) it is most efficient to perform calculations in a coordinate system aligned with the surface normal - surface space. Currently there is a lot of code duplication generating surface to primitive and inverse transforms. This code should be moved to the intersection class where it is most relevant.

Add two new methods:

cpdef AffineMatrix surface_to_local(self)
cpdef AffineMatrix local_to_surface(self)

It would also be sensible to rename the transform attribute due to the addition of the new ones.

Intersection.to_local --> Intersection.world_to_primitive
Intersection.to_world --> Intersection.primitive_to_world
Intersection.local_to_surface() --> Intersection.primitive_to_surface()
Intersection.surface_to_local() --> Intersection.surface_to_primitive()

Alternatively... should these always be calculated and provided as attributes? Would require a number of square roots (normalisations) and a cross product. Adding UV support in the future will probably require much of this math anyway... so maybe we just do it?

**Comment by mattngc** [comment]
Functionality moved to material layer.
